### ISSUE TITLE
Migrating to Python3

### ISSUE THREAD

**Issue by ls-initiatives** [zlacelle/nagios_check_zfs_linux#9]
Running the script with python3 yields errors, probably due to minor things like `print` statements.
Since python2 is not installed by default anymore on modern distros, and will soon be EOL, this would benefit from being ported to python 3.

**Comment by zlacelle** [comment]
Agreed, I will work on porting this.

**Comment by speedytom** [comment]
There is patch for pyton3 and fragmentation missing. I got this on my omnios:
root@nfsserv2:/opt/local/etc/nagios# /opt/local/libexec/nagios/check_zfs.py --capacity 93 95 --fragmentation 65 70 cdb-2019
OK: POOL: cdb-2019, STATUS: ONLINE, SIZE: 54.5T, ALLOC: 31.3T, FREE: 23.2T, FRAG: -, CAP: 57% | frag=-%;65;70; cap=57%;93;95; size=55808.0GB;;; alloc=32051.2GB;;; free=23756.8GB;;; health=0;1;3;

root@nfsserv2:~# zpool list cdb-2019
NAME       SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
cdb-2019  54.5T  31.3T  23.2T        -         -      -    57%  1.00x  ONLINE  -

[pyton3+fragmentation.txt](https://github.com/zlacelle/nagios_check_zfs_linux/files/4349971/pyton3%2Bfragmentation.txt)

**Comment by speedytom** [comment]
If you give me permission to git I will push to your branch.

**Comment by zlacelle** [comment]
Hello @speedytom, thanks for the patch! Do you mind forking and creating a pull request? Ill merge and test then.

**Comment by speedytom** [comment]
I have to say that I am doing the first time at GitHub. I suppose it could be right here:
https://github.com/speedytom/nagios_check_zfs_linux/commit/387aec1271bbdbd600495348982f3229973b2397#diff-742438e8805cac323cb2d49cc42d27b5

Please, give me feedback at stanislav.tokos@gmail.com.

Regards
Stanislav

**Comment by zlacelle** [comment]
@speedytom this looks good. if you do "create pull request" based off the branch, I think Github will merge it for me. See: https://help.github.com/en/desktop/contributing-to-projects/creating-a-pull-request
EDIT: I just checked the patch and it looks fine, but still go ahead with the pull request, for my own OCD!

**Comment by speedytom** [comment]
I have already created fork from your project. I don't have permission create branch on your project. 
That is my fork
https://github.com/speedytom/nagios_check_zfs_linux/blob/master/check_zfs.py

I tried on Linux by git command line. I tried with GitHub desktop on WIN10.

**Comment by zlacelle** [comment]
@speedytom no problem, I created and merged the pull request! If you go to "Pull Requests" in your repository on Github, and then "Create Pull Request", you can generate them. Just an FYI for future contributions. Thank you for making these changes, and once I test I will create a new release!
